#!/bin/bash

# Extract fields from data.json file
name=$(jq -r '.name' data.json)
height=$(jq -r '.height' data.json)
weight=$(jq -r '.weight' data.json)
type=$(jq -r '.types[0].type.name' data.json)

# covert height decimetres to metres using awk
formatted_height=$(awk "BEGIN {printf \"%.1f\", $height / 10}")

# convert weight hectograms to kilograms using awk
formatted_weight=$(awk "BEGIN {printf \"%.1f\", $weight / 10}")

# capitalize first letters of name and type using sed
name=$(echo "$name" | sed 's/.*/\u&/')
type=$(echo "$type" | sed 's/.*/\u&/')

# Final output
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
